import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import SignIn from "./SignIn/";

// import Navbar from "../layouts/navbar/Navbar.jsx";
// import Sidebar from "../layouts/sidebar/Sidebar";
// import LayoutContainer from "../layouts/LayoutContainer";
// import CardContent from "../components/Navbar/Card/CardContent";
// import Footer from "../components/footer/Footer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sign In - Ticketing App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logos.png" />
      </Head>
      <SignIn />
    </div>
  );
}
