import { Box } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import SignIn from "../components/SignIn";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sign In - Ticketing App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logos.png" />
      </Head>
      <Box>
        <SignIn />
      </Box>
    </div>
  );
}
