import { React } from "react";
import Sidebar from "../../layouts/sidebar/Sidebar";
import CardContent from "../../components/Card/ContentDashboard";
import Head from "next/head";

import { Box } from "@chakra-ui/react";

const index = () => {
  return (
    <>
      <Head>
        <title>Dashboard - Ticketing App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logos.png" />
      </Head>
      <main>
        <Box>
          <Sidebar>
            <CardContent />
          </Sidebar>
        </Box>
      </main>
    </>
  );
};

export default index;
