import React from "react";
import Sidebar from "../../layouts/sidebar/Sidebar";
import CardContent from "../../components/Card/ContentDashboard";
import Head from "next/head";

const index = () => {
  return (
    <>
      <Head>
        <title>Dashboard - Ticketing App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logos.png" />
      </Head>
      <Sidebar>
        <CardContent />
      </Sidebar>
    </>
  );
};

export default index;
