import React from "react";
import Sidebar from "../../layouts/sidebar/Sidebar";
import ContentDataAntrian from "../../components/Card/ContentDataAntrian";
import Head from "next/head";
import styles from "../../styles/Home.module.css";

const index = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Data Antrian - Ticketing App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logos.png" />
      </Head>

      <Sidebar>
        <ContentDataAntrian />
      </Sidebar>
    </div>
  );
};

export default index;
