import React from "react";
import Sidebar from "../../layouts/sidebar/Sidebar";
import ContentTambahAntrian from "../../components/Card/ContentTambahAntrian";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { Box } from "@chakra-ui/react";

const index = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Data Antrian - Ticketing App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logos.png" />
      </Head>

      <Box>
        <Sidebar>
          <ContentTambahAntrian />
        </Sidebar>
      </Box>
    </div>
  );
};

export default index;
